/** 中文界面文案。key 是代码和 HTML 里的英文原文，占位符写作 {name}。 */
globalThis.IH_zh ||= Object.freeze({
  'Analyzing… · click to cancel': '正在分析… · 点击取消',
  'Click to clear': '点击清除',
  'Analyze this page': '分析此页',
  'Reanalyze this page': '重新分析此页',
  'Options': '选项',
  'Always analyze this site': '总是分析此网站',
  'Always analyze {host}': '总是分析 {host}',
  'Stop always analyzing {host}': '不再总是分析 {host}',
  'Always analyze {host}?': '总是分析 {host}？',
  'Next time you open this site, it analyzes automatically. No need to click.': '下次打开这个网站时自动分析，不用手点了。',
  'Later': '以后再说',
  "Don't ask again": '不再询问',
  'On-device model setup': '准备本机模型',
  'This downloads about 800 MB (Gemma 3 270M q4) and keeps it on this computer.': '会下载约 800 MB（Gemma 3 270M q4），留在这台电脑上。',
  'Download source': '下载来源',
  'Weight download source': '模型下载来源',
  'Official': '官方',
  'China': '国内',
  'Download': '下载',
  'Cancel': '取消',
  'Hide': '隐藏',
  'Close': '关闭',
  'Preparing on-device model…': '正在准备本机模型…',
  'Download was not authorized': '下载未获授权',
  'Failed to switch download source': '未能切换下载来源',
  'Downloading {file} · {loaded} / {total}': '正在下载 {file} · {loaded} / {total}',
  'Preparing {file}': '正在准备 {file}',
  'Preparing download': '正在准备下载',
  'Got {file}': '已下载 {file}',
  'Download complete': '下载完成',
  'Download stopped.': '已停止下载。',
  'Setup failed': '准备失败',
  'On-device model is ready. You can close this window. Later toolbar clicks will analyze on this device only.': '本机模型已就绪。可以关闭这个窗口。之后点工具栏图标，只在本机分析。',
  'On-device model is ready. You can close this window. Later toolbar clicks will prefer this device.': '本机模型已就绪。可以关闭这个窗口。之后点工具栏图标，会优先用本机。',
  'Stopping download…': '正在停止下载…',
  'Failed to stop download': '未能停止下载',
  'Settings': '设置',
  'How to use': '怎么用',
  'Highlight this page to preview': '高亮本页，预览效果',
  'Highlight': '高亮',
  'Highlight style': '高亮样式',
  'PDFs fall back to underline.': 'PDF 会改用下划线。',
  'Highlight color': '高亮颜色',
  'Highlight color presets': '高亮颜色预设',
  'Text color': '文字颜色',
  'Highlight intensity': '高亮强度',
  'Minimum visibility': '最低可见度',
  'How visible the least important text stays.': '最不重要的文字至少还剩多清楚。',
  'Normalize scale': '按本页缩放',
  'Scale the highlight so the most surprising text is at full highlight.': '让本页信息量最高的文字达到最强高亮。',
  'Percent at full highlight': '达到最强高亮的比例',
  '{pct}% at full highlight': '{pct}% 达到最强高亮',
  'One-tone highlight': '一档高亮',
  'Experimental': '实验性',
  'Not recommended. Threshold does not generalize across models.': '不建议。阈值换模型后就不通用。',
  'Highlight threshold': '高亮阈值',
  'Display': '显示',
  'Hover for details': '悬停看详情',
  'Only for highlights just analyzed. Not for highlights restored from cache.': '只对刚刚分析的高亮有效。从缓存恢复的没有详情。',
  'Progress chart': '进度图',
  'Merge subwords': '合并子词',
  'Hover still shows tokens.': '悬停时仍会显示 token。',
  'Content': '内容',
  'Main article only': '仅正文',
  'Turn on to skip other visible text.': '打开后跳过其余可见文字。',
  'Analysis': '分析',
  'Where to analyze': '在哪里分析',
  'On-device only never uploads, and never uses the cloud.': '「仅本机」不会上传，也不会使用云端。',
  'Auto': '自动',
  'On this device only': '仅本机',
  'Cloud only': '仅云端',
  'Cloud model': '云端模型',
  'Cloud network latency': '云端网络延迟',
  'Measuring…': '测量中…',
  'Edge server': '边缘服务器',
  'Compute server': '算力服务器',
  '{label}…': '{label}…',
  '{label} {ms} ms': '{label} {ms} ms',
  '{label} failed': '{label}失败',
  'On-device WebGPU': '本机 WebGPU',
  'Checking…': '正在检查…',
  'Available': '可用',
  'Not available': '不可用',
  'Not checked yet': '尚未检查',
  'On-device model': '本机模型',
  'Reading…': '正在读取…',
  'Prepare': '准备',
  'Ready (Gemma 3 270M)': '已就绪（Gemma 3 270M）',
  'Not prepared (Gemma 3 270M)': '尚未准备（Gemma 3 270M）',
  'This computer cannot run the on-device model': '这台电脑无法运行本机模型',
  'Clear the on-device model? Using it next time will download about 800 MB again.': '清除本机模型？下次再用会重新下载约 800 MB。',
  'Downloading on-device model…': '正在下载本机模型…',
  'Auto analyze': '自动分析',
  'Sites': '网站',
  'Always analyze sites below. Or use right-click menu -> Always analyze this site.': '总是分析下面的网站。也可以用右键菜单 → 总是分析此网站。',
  'Site to add': '要添加的网站',
  'Enter a site like example.com, *.example.com, or * for every site': '请输入 example.com、*.example.com，或用 * 表示所有网站',
  'Storage': '存储',
  'Analysis cache': '分析缓存',
  'Settings restore': '恢复设置',
  'Restore recommended': '恢复推荐设置',
  'Puts settings back to the defaults. Auto-analyze sites stay.': '设置回到默认。自动分析的网站会保留。',
  'Restore recommended settings? Auto-analyze sites stay.': '恢复推荐设置？自动分析的网站会保留。',
  'About': '关于',
  'Info Highlight is part of <a class="about-home" href="https://info-lens.app/" target="_blank" rel="noopener noreferrer">Info Lens</a>, a toolbox for exploring the informational nature of LLMs and language.': '信息高亮是 <a class="about-home" href="https://info-lens.app/" target="_blank" rel="noopener noreferrer">Info Lens</a> 的一部分，一个用于探索 LLM 与语言的信息本质的工具箱。',
  'Feedback': '反馈',
  "We'd love to hear from you. Please tell us anything you'd like.": '很想听听你的想法，说什么都可以。',
  'Contact': '联系方式',
  'optional': '选填',
  'Contact, optional': '联系方式，选填',
  'Thank you. Your feedback helps us improve.': '谢谢。你的反馈能帮我们改进。',
  'Color blocks': '色块',
  'Underline': '下划线',
  'Fade unimportant': '淡出不重要的',
  'Paused': '已暂停',
  'Continue to highlight more': '继续即可标出更多',
  'Continue': '继续',
  'Cold starting': '正在冷启动',
  'The default style is now "Fade".': '默认样式已改为「淡出」。',
  'OK': '好',
  'Go to settings': '去设置',
  'Remove': '移除',
  'Sent': '已发送',
  'Send': '发送',
  '{entries} entries · {size}': '{entries} 条 · {size}',
  'Failed to read status': '未能读取状态',
  'Failed to clear': '未能清除',
  'Add': '添加',
  'Clear': '清除',
  'Restore': '恢复',
  'Failed': '失败',
  'Retry': '重试',
});
